# Generated by Django 4.1.5 on 2023-01-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sn', models.IntegerField(unique=True)),
                ('computer_name', models.TextField(unique=True)),
                ('inv', models.IntegerField(max_length=10)),
                ('employee_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printsn', models.IntegerField(max_length=20)),
                ('printers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('braches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='employees.branch')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='floors',
            field=models.ManyToManyField(related_name='departments', to='employees.floor'),
        ),
    ]
